### ISSUE TITLE
SWF format spec link in README is now dead.

### ISSUE THREAD

**Issue by eddyb** [open-flash/swf-tree#1]
The current link is https://www.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf

It's also newer, at version 19 (initially I thought they were the same link and that the README just had an older version number, but it turns out that it also got moved around on Adobe's website).

**Comment by demurgos** [comment]
Thanks for the notification. I'll send a PR to fix it.

I keep all of the specs relevant to SWF in [open-flash/open-flash/specs](https://github.com/open-flash/open-flash/tree/master/specs/). It includes [the SWF 19 spec](https://github.com/open-flash/open-flash/blob/master/specs/swf-spec-19.pdf).
