### ISSUE TITLE
[all] Morph shape straight-to-curved transformation leads to non-integers

### ISSUE THREAD

**Issue by demurgos** [open-flash/swf-tree#22]
When the edge of a morph shape mixes both curved and straight edges (start/end states), the straight edge is parsed as a curved edge with an intermediate anchor point. This anchor point is computed as the midpoint. For example the straight edge `{delta_x: 3, delta_y: 4}` leads to `{control_delta_x: 1.5, control_delta_y: 2, anchor_delta_x: 1.5, anchor_delta_y: 2}`.

Rust rounds to integers but TS keeps the fractional part. This leads to errors while de/serializing.
We should either allow the fractional part in `swf-tree` or normalize to integers. The error should be evenly spread: floor on the control delta and ceil on the anchor delta.

**Comment by eddyb** [comment]
This is going to simplify https://github.com/lykenware/flashback/blob/b29c1bf4fca818ce5c0d554e08d867263f6e2c48/src/shape.rs#L259-L271, nice!
